name: Build and Release v2ray-core

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: |
        go mod download

    - name: Build for Linux
      run: |
        env GOOS=linux GOARCH=amd64 go build -o v2ray-linux-amd64 ./main

    - name: Build for macOS
      run: |
        env GOOS=darwin GOARCH=amd64 go build -o v2ray-darwin-amd64 ./main

    - name: Build for Windows
      run: |
        env GOOS=windows GOARCH=amd64 go build -o v2ray-windows-amd64.exe ./main

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: v2ray-binaries
        path: |
          v2ray-linux-amd64
          v2ray-darwin-amd64
          v2ray-windows-amd64.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v2.0.0
        release_name: Release v2.0.0
        body: |
          Release v2.0.0
          - Add support for multiple platforms
        draft: false
        prerelease: false

    - name: Upload Release Artifacts
      id: upload_release_artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          ./v2ray-linux-amd64
          ./v2ray-darwin-amd64
          ./v2ray-windows-amd64.exe
        asset_name: |
          v2ray-linux-amd64
          v2ray-darwin-amd64
          v2ray-windows-amd64.exe
        asset_content_type: application/octet-stream
